# Generated by Django 4.1.3 on 2022-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
