# Generated by Django 4.1.3 on 2022-11-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='supply',
            new_name='supplier',
        ),
    ]
